# two node (one workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30010
    hostPort: 30010   
    protocol: TCP
- role: worker
  extraPortMappings:
  - containerPort: 3000
    hostPort: 3000  
    protocol: TCP
  extraPortMappings:
  - containerPort: 9090
    hostPort: 9090
    protocol: TCP
    